# Generated by Django 4.2.7 on 2025-08-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="display_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="public_search",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tags",
            field=models.CharField(
                blank=True, help_text="Comma-separated tags", max_length=255
            ),
        ),
    ]
