# Generated by Django 4.2.7 on 2025-08-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memorials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="memorial",
            name="public_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=22, unique=True
            ),
        ),
    ]
